[package]
name = "staking_contract"
version = "0.1.0"
edition = "2018"

[dependencies]
ink_lang = { version = "4.0", default-features = false }
ink_storage = { version = "4.0", default-features = false }

[features]
default = ["std"]
std = [
    "ink_lang/std",
    "ink_storage/std",
]
